import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Arrowup from "./components/Arrowup";
import WhatsAppButton from "./components/WhatsAppButton";
import Footer from "./components/Footer";
// import FirstVideo from "./components/VideoShow";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Amp Technology",
  description: "Generated by create next app",
};

async function getData() {
  try {
    let officeData = await fetch(`${process.env.BACKLINK}/public/officeData`, {
      headers: {
        "x-api-key": process.env.API_KEY,
        "office-id": process.env.OFFICE,
      },
      next: {
        revalidate: 60,
      },
    });
    if (!officeData.ok) {
      return console.error(`Failed to fetch office data: ${res.statusText}`);
    }

    return officeData.json();
  } catch (error) {
    console.error("Error:", error.message);
    return null;
  }
}

async function getLinks() {
  try {
    let links = await fetch(`${process.env.BACKLINK}/public/social`, {
      headers: {
        "x-api-key": process.env.API_KEY,
        "office-id": process.env.OFFICE,
      },
      cache: "no-store",
    });

    return await links.json();
  } catch (error) {
    return null;
  }
}

async function getBg() {
  const res = await fetch(process.env.BACKLINK + "/public/headings", {
    headers: {
      "x-api-key": process.env.API_KEY,
      "office-id": process.env.OFFICE,
    },
    cache: "no-store",
  });
  if (!res.ok) {
    return res.statusText;
  }
  return res.json();
}

export default async function RootLayout({ children }) {
  let data = await getData();
  const officeData = data?.data;
  let getSocial = await getLinks();
  const socialData = getSocial?.data[0];
  const bg = await getBg();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <FirstVideo /> */}
        <Header
          data={officeData}
          links={socialData}
          bg={bg.data?.headerImage}
        />
        <Arrowup />
        <WhatsAppButton />
        {children}
        <Footer
          data={officeData}
          links={socialData}
          bg={bg.data?.footerImage}
        />
      </body>
    </html>
  );
}
